# Generated by Django 3.2.14 on 2023-03-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJoueur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='english_test_app.joueur')),
            ],
        ),
        migrations.CreateModel(
            name='verbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseVerbal', models.CharField(max_length=100)),
                ('preterit', models.CharField(max_length=100)),
                ('participePasse', models.CharField(max_length=100)),
                ('traduction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponsePreterit', models.CharField(max_length=100)),
                ('reponseParticipePasse', models.CharField(max_length=100)),
                ('dateEnvoi', models.DateTimeField()),
                ('dateReponse', models.DateTimeField()),
                ('idPartie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='english_test_app.partie')),
                ('idVerbe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='english_test_app.verbe')),
            ],
        ),
        migrations.AddField(
            model_name='joueur',
            name='idVille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='english_test_app.ville'),
        ),
    ]
